
set(VERSION 0x010000)
set(VERSION_MAJOR 1)
set(VERSION_MINOR 0)
set(VERSION_REVISION 0)
set(VERSION_STR ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_REVISION})
set(VERSION_CSTR \"${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_REVISION}\")

include_directories(include)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

add_definitions( -Wall -g -std=c++0x -O3 -DVERSION=${VERSION} -DVERSION_STR=${VERSION_CSTR} )

